Correct ``log.error`` call with arguments